add functions
LingL42/go-project-sprint-9 pull request #1
Opened 2024-07-23 10:27 UTC by LingL42

2024-07-23 12:30 UTC, dirtymew requested changes
Привет Дима

хорошая работа - но есть что поправить

2024-07-23 12:30 UTC, dirtymew commented on precode.go
> +	}
тут нужно задержку добавить см readme.md

2024-07-23 12:30 UTC, dirtymew commented on precode.go
>  	var inputSum int64   // сумма сгенерированных чисел
к inputCount и inputSum возможен конкурентный доступ нужно использовать mutex или atomic

2024-07-24 14:43 UTC, LingL42 commented on precode.go
> +	}
Спасибо, за подсказки, в новой версии добавлю

2024-07-24 22:37 UTC, dirtymew approved these changes
Привет Дима

все отлично - зачет

2024-08-05 09:04 UTC, merged